import type { Metadata } from "next";
import Link from "next/link";
import { SeoPage } from "@/components/seo/SeoPage";
export const metadata: Metadata = { title: "Intelligent LLM Router for Cost-Efficient AI APIs", description: "Learn how Basktre routes text requests, when to use automatic routing, when to pin a model, and the current limitations.", alternates: { canonical: "/llm-router" } };
const faqs = [{ question: "What is an LLM router?", answer: "An LLM router selects a model for each request using task requirements and cost rather than sending every request to one model." }, { question: "Can I override automatic routing?", answer: "Yes. Send a specific supported model tag whenever you need deterministic model selection." }, { question: "Does routing guarantee savings or quality?", answer: "No. Model prices and task suitability vary. Benchmark your own workloads and pin a model when exact behavior matters." }];
export default function Page() { return <SeoPage path="/llm-router" eyebrow="// intelligent routing" title="An LLM router built to control API cost" intro="Use model: auto for cost-aware selection based on task requirements, or specify a model whenever consistency and model-specific behavior matter." faqs={faqs}>
  <h2>How automatic routing works</h2><ol><li>Your application sends a text messages request.</li><li>The router assesses the task and supported model choices.</li><li>It selects a cost-effective model intended to handle that task.</li><li>Basktre forwards the request without retaining prompt or response bodies.</li><li>The response identifies the model used and provides usage metadata.</li></ol>
  <pre>{JSON.stringify({ model: "auto", messages: [{ role: "user", content: "Summarize this support ticket in three bullets." }] }, null, 2)}</pre>
  <h2>When automatic routing is appropriate</h2><ul><li>High-volume text workloads where several models can meet the requirement.</li><li>Summarization, extraction and routine generation where cost flexibility matters.</li><li>Applications that record the selected model and evaluate outputs continuously.</li></ul>
  <h2>When to pin a model</h2><ul><li>You require repeatable model-specific behavior or have validated only one model.</li><li>Your prompt relies on a capability or parameter that is not shared by every model.</li><li>You are running benchmarks, regulated review workflows or incident reproduction.</li></ul>
  <h2 id="limitations">Current limitations</h2><p>Automatic selection is not a guarantee of a particular quality, latency or saving. Basktre’s public documentation does not currently promise a configurable fallback chain, voice routing, image generation, JSON mode or tool-call normalization. Use a pinned model and test every required parameter when those details matter.</p>
  <h2 id="methodology">How to evaluate savings responsibly</h2><p>Basktre has not published a sufficiently detailed benchmark to support a universal percentage-savings claim, so this page does not make one. Build a representative prompt set, define pass/fail quality criteria, record the chosen model and token cost, and compare the same successful requests with your pinned baseline. Include Basktre’s 4% wallet top-up fee in the final calculation.</p>
  <p>Compare current rates on the <Link className="underline" href="/llm-api-pricing">LLM API pricing page</Link> or model a workload with the <Link className="underline" href="/llm-api-cost-calculator">cost calculator</Link>.</p>
</SeoPage>; }
