import type { Metadata } from "next";
import Link from "next/link";
import { SeoPage } from "@/components/seo/SeoPage";
export const metadata: Metadata = { title: "Unified LLM API for GPT, Claude, Gemini & More", description: "Access multiple text LLM providers through one key and messages API. See request, streaming, model-switching and current compatibility limits.", alternates: { canonical: "/unified-llm-api" } };
export default function Page() { return <SeoPage path="/unified-llm-api" eyebrow="// one text integration" title="One unified LLM API for a growing model catalog" intro="Connect once, then call currently available GPT, Claude, Gemini, Llama, DeepSeek and other models with one Basktre key and a consistent messages request shape. Live availability may vary during beta.">
  <h2>What Basktre normalizes</h2><ul><li>One API key and wallet across supported model providers.</li><li>A messages-based request shape for text model calls.</li><li>Streaming and non-streaming endpoints.</li><li>Manual model tags or automatic routing.</li><li>Input and output token pricing per model.</li></ul>
  <h2>Switch models in one field</h2><pre>{JSON.stringify({ model: "claude-haiku-4-5", messages: [{ role: "user", content: "Return a concise release-note summary." }], max_tokens: 300, temperature: 0.2 }, null, 2)}</pre><p>Replace the model tag with another supported tag, or use <code>auto</code> for cost-aware selection.</p>
  <h2>Streaming request</h2><pre>{`curl https://api.basktre.in/api/v1/models/stream \\\n  -H "api-key: your_basktre_key" \\\n  -H "Content-Type: application/json" \\\n  -d '{"model":"auto","messages":[{"role":"user","content":"Hello"}]}'`}</pre>
  <h2>Compatibility boundaries</h2><p>Basktre uses its own <code>api-key</code> header and model call endpoints, so it should not be described as a drop-in OpenAI base-URL replacement. The public documentation currently covers text messages, token limits, temperature, top-p, stop sequences and streaming. It does not currently document normalized tools, JSON mode, image generation, audio input, speech output or voice APIs.</p>
  <h2>Migration checklist</h2><ol><li>Map authentication to the Basktre <code>api-key</code> header.</li><li>Use the documented call or stream endpoint.</li><li>Map your current model name to a supported Basktre tag.</li><li>Test provider-specific parameters and error handling rather than assuming they are normalized.</li><li>Keep image and voice workloads on a service that explicitly supports them.</li></ol>
  <p>See the exact request fields and examples in the <Link className="underline" href="/docs">API documentation</Link>.</p>
</SeoPage>; }
