"use client";
import { useMemo, useState } from "react";
import type { Provider } from "@/types";
import { estimateCost, formatPrice } from "@/lib/pricing";

export default function CostCalculator({ providers }: { providers: Provider[] }) {
  const [input, setInput] = useState(1000); const [output, setOutput] = useState(500); const [requests, setRequests] = useState(1000); const [selected, setSelected] = useState<string[]>(providers.slice(0,3).map(p=>p.tag));
  const valid = [input,output,requests].every((n)=>Number.isFinite(n)&&n>=0);
  const results = useMemo(()=>valid ? providers.filter(p=>selected.includes(p.tag)).map(p=>({p,...estimateCost(p,input,output,requests)})).sort((a,b)=>a.total-b.total) : [],[providers,selected,input,output,requests,valid]);
  const toggle=(tag:string)=>setSelected(s=>s.includes(tag)?s.filter(x=>x!==tag):[...s,tag]);
  if (!providers.length) return <div className="rounded-xl border border-[var(--border)] bg-white p-6">Live model pricing is temporarily unavailable. Retry shortly to calculate current estimates.</div>;
  return <div className="grid gap-8 lg:grid-cols-[360px_1fr]"><form className="rounded-xl border border-[var(--border)] bg-white p-6" onSubmit={(e)=>e.preventDefault()}><label className="block text-sm font-semibold">Input tokens per request<input type="number" min="0" value={input} onChange={e=>setInput(Number(e.target.value))} className="mt-2 w-full rounded-lg border border-[var(--border)] px-3 py-2"/></label><label className="mt-5 block text-sm font-semibold">Output tokens per request<input type="number" min="0" value={output} onChange={e=>setOutput(Number(e.target.value))} className="mt-2 w-full rounded-lg border border-[var(--border)] px-3 py-2"/></label><label className="mt-5 block text-sm font-semibold">Number of requests<input type="number" min="0" value={requests} onChange={e=>setRequests(Number(e.target.value))} className="mt-2 w-full rounded-lg border border-[var(--border)] px-3 py-2"/></label>{!valid&&<p className="mt-3 text-sm text-red-700">Enter non-negative numbers.</p>}<button type="button" onClick={()=>{setInput(1000);setOutput(500);setRequests(1000);setSelected(providers.slice(0,3).map(p=>p.tag));}} className="mt-5 text-sm underline">Reset calculator</button><fieldset className="mt-6 max-h-64 overflow-y-auto border-t border-[var(--border)] pt-4"><legend className="font-semibold">Compare models</legend>{providers.map(p=><label key={p.tag} className="mt-2 flex gap-2 text-sm"><input type="checkbox" checked={selected.includes(p.tag)} onChange={()=>toggle(p.tag)}/>{p.name}</label>)}</fieldset></form><div><h2 className="font-[var(--font-serif)] text-3xl">Estimated cost</h2><p className="mt-2 text-sm text-[var(--text-2)]">Selected-model estimates only; automatic routing may choose a different model.</p><div className="mt-5 space-y-4">{results.map(({p,usageCost,topUpFee,total})=><div key={p.tag} className="rounded-xl border border-[var(--border)] bg-white p-5"><div className="flex items-start justify-between gap-4"><div><strong>{p.name}</strong><div className="font-mono text-xs text-[var(--text-3)]">{p.tag}</div></div><strong className="text-xl text-[var(--accent)]">{formatPrice(total)}</strong></div><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-[var(--text-3)]">Model usage</dt><dd>{formatPrice(usageCost)}</dd></div><div><dt className="text-[var(--text-3)]">4% funding fee</dt><dd>{formatPrice(topUpFee)}</dd></div></dl></div>)}{selected.length===0&&<p className="rounded-xl border border-[var(--border)] p-5">Select at least one model to compare.</p>}</div></div></div>;
}
